version: "3.8"
services:
  server:
    container_name: sorokchat.server
    build:
      context: .
    depends_on:
      - database
    ports:
      - "8080:8080"
  database:
    container_name: sorokchat.database
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_DB: sorokchat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgres/data
volumes:
  db_data: