spring:
  application:
    name: sorok-chat-server-spring
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5430/sorokchat
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
tokens:
  signing-key: '{"kty": "oct", "kid": "signing", "alg": "HS256", "k": "Тхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМТхі8НнЕнДЖДжХлдмОксУк7НДжгХвзВ1ЕЗвМ"}'
  encrypting-key: '{"kty": "oct", "kid": "encrypting", "alg": "A128GCM", "k": "f3ooSLbbpIBVtU4LBelAwjbkI8dqrUk4"}'